import { describe, it, expect, beforeAll, vi } from 'vitest';
import request from 'supertest';
import { createServer } from '../server';
import { Express } from 'express';

// To avoid Vite initialization slowing down backend tests, we mock the Vite server creation
vi.mock('vite', () => ({
    createServer: vi.fn(() => Promise.resolve({
        middlewares: (req: any, res: any, next: any) => next()
    }))
}));

describe('Inquiry API Endpoint', () => {
    let app: Express;

    beforeAll(async () => {
        // Set NODE_ENV to test to prevent app.listen from starting an actual server
        process.env.NODE_ENV = 'test';
        app = await createServer();
    });

    it('rejects an inquiry missing required fields', async () => {
        const res = await request(app)
            .post('/api/inquiry')
            .send({ name: 'John Doe' }); // Missing email and message

        expect(res.status).toBe(400);
        expect(res.body).toHaveProperty('error', 'Missing required fields');
    });

    it('accepts a valid inquiry and processes it', async () => {
        const validData = {
            name: 'Vitest User',
            email: 'vitest@example.com',
            message: 'This is a test inquiry generated by the unit test suite.'
        };

        const res = await request(app)
            .post('/api/inquiry')
            .send(validData);

        // It should succeed (either saving to DB + Email, or just DB depending on SMTP ENV configuration on the runner)
        expect(res.status).toBe(200);
        expect(res.body).toHaveProperty('success', true);

        // We expect the response to either indicate successful email sent or dbOnly true if SMTP is unconfigured natively
        expect(
            res.body.message.includes('email sent') || res.body.dbOnly
        ).toBe(true);
    });
});
