import React, { useRef } from 'react';

export const scriptures: Record<string, string> = {
  "Genesis 17:7": "And I will establish my covenant between me and thee and thy seed after thee in their generations for an everlasting covenant, to be a God unto thee, and to thy seed after thee.",
  "Genesis 3:15": "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel.",
  "Deuteronomy 24:16": "The fathers shall not be put to death for the children, neither shall the children be put to death for the fathers: every man shall be put to death for his own sin.",
  "Galatians 3:16": "Now to Abraham and his seed were the promises made. He saith not, And to seeds, as of many; but as of one, And to thy seed, which is Christ.",
  "Galatians 3:29": "And if ye be Christ's, then are ye Abraham's seed, and heirs according to the promise.",
  "Ephesians 2:15": "Having abolished in his flesh the enmity, even the law of commandments contained in ordinances; for to make in himself of twain one new man, so making peace;",
  "Romans 6:23": "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.",
  "Matthew 16:18": "And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it.",
  "Colossians 1:18": "And he is the head of the body, the church: who is the beginning, the firstborn from the dead; that in all things he might have the preeminence.",
  "Luke 8:11": "Now the parable is this: The seed is the word of God.",
  "Isaiah 63:10": "But they rebelled, and vexed his holy Spirit: therefore he was turned to be their enemy, and he fought against them.",
  "Jeremiah 1:9": "Then the Lord put forth his hand, and touched my mouth. And the Lord said unto me, Behold, I have put my words in thy mouth.",
  "2 Peter 1:21": "For the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost.",
  "John 3:5": "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
  "Galatians 2:20": "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.",
  "John 10:9": "I am the door: by me if any man enter in, he shall be saved, and shall go in and out, and find pasture.",
  "John 10:16": "And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd.",
  "1 Peter 4:17": "For the time is come that judgment must begin at the house of God: and if it first begin at us, what shall the end be of them that obey not the gospel of God?",
  "1 Corinthians 11:29": "For he that eateth and drinketh unworthily, eateth and drinketh damnation to himself, not discerning the Lord's body.",
  "1 Corinthians 11:32": "But when we are judged, we are chastened of the Lord, that we should not be condemned with the world.",
  "2 Corinthians 13:5": "Examine yourselves, whether ye be in the faith; prove your own selves. Know ye not your own selves, how that Jesus Christ is in you, except ye be reprobates?",
  "Isaiah 40:22": "It is he that sitteth upon the circle of the earth, and the inhabitants thereof are as grasshoppers; that stretcheth out the heavens as a curtain, and spreadeth them out as a tent to dwell in:",
  "Job 26:7": "He stretcheth out the north over the empty place, and hangeth the earth upon nothing.",
  "Isaiah 40:8": "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.",
  "John 17:3": "And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent.",
  "1 Corinthians 8:6": "But to us there is but one God, the Father, of whom are all things, and we in him; and one Lord Jesus Christ, by whom are all things, and we by him.",
  "Deuteronomy 9:10": "And the Lord delivered unto me two tables of stone written with the finger of God; and on them was written according to all the words, which the Lord spake with you in the mount out of the midst of the fire in the day of the assembly.",
  "Exodus 34:27": "And the Lord said unto Moses, Write thou these words: for after the tenor of these words I have made a covenant with thee and with Israel.",
  "Jeremiah 30:2": "Thus speaketh the Lord God of Israel, saying, Write thee all the words that I have spoken unto thee in a book.",
  "Revelation 8:1": "And when he had opened the seventh seal, there was silence in heaven about the space of half an hour.",
  "Luke 24:39": "Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have.",
  "1 Timothy 1:17": "Now unto the King eternal, immortal, invisible, the only wise God, be honour and glory for ever and ever. Amen.",
  "John 4:24": "God is a Spirit: and they that worship him must worship him in spirit and in truth.",
  "1 John 3:20": "For if our heart condemn us, God is greater than our heart, and knoweth all things.",
  "Psalm 90:2": "Before the mountains were brought forth, or ever thou hadst formed the earth and the world, even from everlasting to everlasting, thou art God.",
  "Exodus 34:6": "And the Lord passed by before him, and proclaimed, The Lord, The Lord God, merciful and gracious, longsuffering, and abundant in goodness and truth,",
  "Isaiah 54:10": "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the Lord that hath mercy on thee.",
  "Exodus 3:14": "And God said unto Moses, I AM THAT I AM: and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you.",
  "John 8:40": "But now ye seek to kill me, a man that hath told you the truth, which I have heard of God: this did not Abraham.",
  "1 Timothy 2:5": "For there is one God, and one mediator between God and men, the man Christ Jesus;",
  "Hosea 11:9": "I will not execute the fierceness of mine anger, I will not return to destroy Ephraim: for I am God, and not man; the Holy One in the midst of thee: and I will not enter into the city.",
  "John 19:28": "After this, Jesus knowing that all things were now accomplished, that the scripture might be fulfilled, saith, I thirst.",
  "John 4:6": "Now Jacob's well was there. Jesus therefore, being wearied with his journey, sat thus on the well: and it was about the sixth hour.",
  "John 11:35": "Jesus wept.",
  "Mark 13:32": "But of that day and that hour knoweth no man, no, not the angels which are in heaven, neither the Son, but the Father.",
  "Matthew 28:18": "And Jesus came and spake unto them, saying, All power is given unto me in heaven and in earth.",
  "Philippians 2:9": "Wherefore God also hath highly exalted him, and given him a name which is above every name:",
  "Isaiah 43:5": "Fear not: for I am with thee: I will bring thy seed from the east, and gather thee from the west;",
  "Romans 10:15": "And how shall they preach, except they be sent? as it is written, How beautiful are the feet of them that preach the gospel of peace, and bring glad tidings of good things!",
  "Mark 4:11": "And he said unto them, Unto you it is given to know the mystery of the kingdom of God: but unto them that are without, all these things are done in parables:",
  "Ephesians 1:9": "Having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself:",
  "Revelation 7:2": "And I saw another angel ascending from the east, having the seal of the living God: and he cried with a loud voice to the four angels, to whom it was given to hurt the earth and the sea,",
  "Isaiah 46:11": "Calling a ravenous bird from the east, the man that executeth my counsel from a far country: yea, I have spoken it, I will also bring it to pass; I have purposed it, I will also do it.",
  "Ecclesiastes 12:13": "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man.",
  "1 Thessalonians 4:16": "For the Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first:",
  "Revelation 20:6": "Blessed and holy is he that hath part in the first resurrection: on such the second death hath no power, but they shall be priests of God and of Christ, and shall reign with him a thousand years.",
  "Revelation 20:12": "And I saw the dead, small and great, stand before God; and the books were opened: and another book was opened, which is the book of life: and the dead were judged out of those things which were written in the books, according to their works.",
  "Romans 2:16": "In the day when God shall judge the secrets of men by Jesus Christ according to my gospel.",
  "Romans 2:12": "For as many as have sinned without law shall also perish without law: and as many as have sinned in the law shall be judged by the law;",
  "Luke 10:20": "Notwithstanding in this rejoice not, that the spirits are subject unto you; but rather rejoice, because your names are written in heaven.",
  "Revelation 3:5": "He that overcometh, the same shall be clothed in white raiment; and I will not blot out his name out of the book of life, but I will confess his name before my Father, and before his angels.",
  "Galatians 3:27": "For as many of you as have been baptized into Christ have put on Christ.",
  "Revelation 21:1-4": "And I saw a new heaven and a new earth: for the first heaven and the first earth were passed away; and there was no more sea.",
  "Matthew 24:6": "And ye shall hear of wars and rumours of wars: see that ye be not troubled: for all these things must come to pass, but the end is not yet.",
  "Matthew 24:42": "Watch therefore: for ye know not what hour your Lord doth come.",
  "Matthew 4:2": "And when he had fasted forty days and forty nights, he was afterward an hungred.",
  "Matthew 8:24": "And, behold, there arose a great tempest in the sea, insomuch that the ship was covered with the waves: but he was asleep.",
  "Matthew 27:50": "Jesus, when he had cried again with a loud voice, yielded up the ghost.",
  "Acts 20:28": "Take heed therefore unto yourselves, and to all the flock, over the which the Holy Ghost hath made you overseers, to feed the church of God, which he hath purchased with his own blood.",
  "Romans 16:16": "Salute one another with an holy kiss. The churches of Christ salute you.",
  "Acts 20:29": "For I know this, that after my departing shall grievous wolves enter in among you, not sparing the flock.",
  "1 Timothy 4:1": "Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils;",
  "Daniel 12:4": "But thou, O Daniel, shut up the words, and seal the book, even to the time of the end: many shall run to and fro, and knowledge shall be increased.",
  "Revelation 10:4": "And when the seven thunders had uttered their voices, I was about to write: and I heard a voice from heaven saying unto me, Seal up those things which the seven thunders uttered, and write them not.",
  "Jeremiah 33:22": "As the host of heaven cannot be numbered, neither the sand of the sea measured: so will I multiply the seed of David my servant, and the Levites that minister unto me.",
  "Numbers 23:19": "God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?",
  "Psalms 90:2": "Before the mountains were brought forth, or ever thou hadst formed the earth and the world, even from everlasting to everlasting, thou art God.",
  "Genesis 17:1": "And when Abram was ninety years old and nine, the LORD appeared to Abram, and said unto him, I am the Almighty God; walk before me, and be thou perfect.",
  "1 John 4:8": "He that loveth not knoweth not God; for God is love.",
  "Deuteronomy 32:4": "He is the Rock, his work is perfect: for all his ways are judgment: a God of truth and without iniquity, just and right is he.",
  "Leviticus 19:2": "Speak unto all the congregation of the children of Israel, and say unto them, Ye shall be holy: for I the LORD your God am holy.",
  "Matthew 6:9": "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name.",
  "Isaiah 40:28": "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding.",
  "1 Peter 1:20": "Who verily was foreordained before the foundation of the world, but was manifest in these last times for you,",
  "Matthew 1:20": "But while he thought on these things, behold, the angel of the Lord appeared unto him in a dream, saying, Joseph, thou son of David, fear not to take unto thee Mary thy wife: for that which is conceived in her is of the Holy Ghost.",
  "Isaiah 7:14": "Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel.",
  "Matthew 1:21": "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins.",
  "Luke 19:10": "For the Son of man is come to seek and to save that which was lost.",
  "Isaiah 41:9": "Thou whom I have taken from the ends of the earth, and called thee from the chief men thereof, and said unto thee, Thou art my servant; I have chosen thee, and not cast thee away.",
  "Hebrews 13:20": "Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant,",
  "Luke 22:20": "Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you.",
  "Matthew 22:14": "For many are called, but few are chosen.",
  "1 Peter 2:9": "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light:",
  "Ephesians 1:4": "According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:",
  "Romans 11:5": "Even so then at this present time also there is a remnant according to the election of grace.",
  "Romans 8:29": "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, that he might be the firstborn among many brethren.",
  "Acts 2:23": "Him, being delivered by the determinate counsel and foreknowledge of God, ye have taken, and by wicked hands have crucified and slain:",
  "1 Peter 1:2": "Elect according to the foreknowledge of God the Father, through sanctification of the Spirit, unto obedience and sprinkling of the blood of Jesus Christ: Grace unto you, and peace, be multiplied.",
  "2 Timothy 1:9": "Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began,",
  "John 15:16": "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you.",
  "Acts 2:47": "Praising God, and having favour with all the people. And the Lord added to the church daily such as should be saved.",
  "Ephesians 1:22": "And hath put all things under his feet, and gave him to be the head over all things to the church,",
  "Ephesians 2:14": "For he is our peace, who hath made both one, and hath broken down the middle wall of partition between us;",
  "Galatians 3:28": "There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus.",
  "Ephesians 1:23": "Which is his body, the fulness of him that filleth all in all.",
  "Ephesians 5:23": "For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body.",
  "Ephesians 4:4": "There is one body, and one Spirit, even as ye are called in one hope of your calling;",
  "Ephesians 4:13": "Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:",
  "Ephesians 4:16": "From whom the whole body fitly joined together and compacted by that which every joint supplieth, according to the effectual working in the measure of every part, maketh increase of the body unto the edifying of itself in love.",
  "Colossians 2:10": "And ye are complete in him, which is the head of all principality and power:",
  "Revelation 21:2": "And I John saw the holy city, new Jerusalem, coming down from God out of heaven, prepared as a bride adorned for her husband.",
  "Ecclesiastes 12:14": "For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil.",
  "Romans 2:14": "For when the Gentiles, which have not the law, do by nature the things contained in the law, these, having not the law, are a law unto themselves:",
  "1 Corinthians 11:31": "For if we would judge ourselves, we should not be judged.",
  "Roma 6:23": "Sapagka't ang kabayaran ng kasalanan ay kamatayan; datapuwa't ang kaloob na walang bayad ng Dios ay buhay na walang hanggan kay Cristo Jesus na Panginoon natin.",
  "Galacia 3:16": "Ngayon kay Abraham nga sinabi ang mga pangako, at sa kaniyang binhi. Hindi sinasabi ng Dios, At sa mga binhi, na gaya ng marami; kundi gaya ng iisa, At sa iyong binhi, na si Cristo.",
  "Isaias 63:10": "Nguni't sila'y nanganghimagsik at pinighati ang kaniyang banal na Espiritu: kaya't siya'y naging kanilang kaaway, at siya'y nakipaglaban sa kanila.",
  "1 Timoteo 4:1": "Nguni't maliwanag na sinasabi ng Espiritu, na sa mga huling panahon ang iba'y magsisitalikod sa pananampalataya, at mangakikinig sa mga espiritung mapanghikayat at sa mga aral ng mga demonyo,",
  "Mateo 24:6": "At mangakakarinig kayo ng mga digmaan at mga alingawngaw ng mga digmaan; ingatan ninyo na huwag kayong magulumihanan: sapagka't kinakailangang ito'y mangyari datapuwa't hindi pa ang wakas.",
  "Juan 3:5": "Sumagot si Jesus, Katotohanan, katotohanang sinasabi ko sa iyo, Maliban na ang tao'y ipanganak ng tubig at ng Espiritu, ay hindi siya makapapasok sa kaharian ng Dios.",
  "Lucas 8:11": "Ito nga ang talinghaga: Ang binhi ay ang salita ng Dios.",
  "Awit 90:2": "Bago nalabas ang mga bundok, o bago mo nilalang ang lupa at ang sanglibutan, mula sa walang pasimula hanggang sa walang hanggan, ikaw ang Dios.",
  "1 Juan 3:20": "Sapagka't kung hinahatulan tayo ng ating puso, ang Dios ay lalong dakila kay sa ating puso, at nalalaman niya ang lahat ng mga bagay.",
  "Mateo 16:18": "At sinasabi ko naman sa iyo, na ikaw ay Pedro, at sa ibabaw ng batong ito ay itatayo ko ang aking iglesia; at ang mga pintuan ng Hades ay hindi magsisipanaig laban sa kaniya.",
  "Roma 2:14": "Sapagka't kung ang mga Gentil na walang kautusan sa katutubo, ay nagsisigawa ng mga bagay ng kautusan, ang mga ito, na walang kautusan, ay siyang kautusan sa kanilang sarili;",
  "1 Pedro 4:17": "Sapagka't dumating na ang panahon na ang paghuhukom ay dapat magpasimula sa bahay ng Dios: at kung magpasimula sa atin, ano kaya ang wakas ng mga hindi nagsisitalima sa evangelio ng Dios?",
  "1 Corinto 11:31": "Datapuwa't kung ating sisisiyasatin ang ating sarili, ay hindi tayo hahatulan."
};

export const ScriptureLink: React.FC<{ verse: string; children: React.ReactNode; onHover: (verse: string | null, x: number, y: number) => void }> = ({ verse, children, onHover }) => {
  const ref = useRef<HTMLSpanElement>(null);
  
  return (
    <span 
      ref={ref}
      className="scripture-link" 
      onMouseEnter={() => {
        if (ref.current) {
          const rect = ref.current.getBoundingClientRect();
          onHover(verse, rect.left + rect.width / 2, rect.top);
        }
      }}
      onMouseLeave={() => onHover(null, 0, 0)}
    >
      {children}
    </span>
  );
};
